### ISSUE TITLE
[AVM Module Issue]: BastionHost Default Tags always set

### ISSUE THREAD

**Issue by birdnathan** [Azure/terraform-azurerm-avm-res-network-bastionhost#40]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.2

### Description

Cannot override default tags
![image](https://github.com/Azure/terraform-azurerm-avm-res-network-bastionhost/assets/42775203/c051bf2b-2511-48ff-83ac-c1c8e022a827)

**Comment by jaredfholgate** [comment]
Closed and released with #48 v0.2.0
